# Generated by Django 3.1.2 on 2020-12-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocao',
            name='favoritar',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
    ]
