# Generated by Django 3.1.2 on 2020-12-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201202_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocao',
            name='favoritar',
            field=models.BooleanField(default=False),
        ),
    ]
